### ISSUE TITLE
Incorrect parsing of Theory test results

### ISSUE THREAD

**Issue by Vertigo093i** [wwwlicious/wwwlicious.bamboo.xunit#2]
Surprisingly, Theory test results might look like the following:

```xml
<test time="0.0000162" name="Project.Tests.PathManipulations.PathParsingCreatesSegments(path: \&quot;$.stores[0].name\&quot;, numberOfSegments: 3)" result="Pass" method="PathParsingCreatesSegments" type="Project.Tests.PathManipulations"/>
```

or even like this:

```xml
<test time="0.0012517" name="Project.Tests.PathManipulations.ResolvingDocumentPathReturnsCorrectProperty(path: \&quot;$.products[0].type\&quot;, propertyType: typeof(Project.DictionaryProperty))" result="Pass" method="ResolvingDocumentPathReturnsCorrectProperty" type="Project.Tests.PathManipulations"/>
```

Please note dots inside parentheses.

Therefore I'm attaching a small and simple [patch](https://github.com/wwwlicious/wwwlicious.bamboo.xunit/files/1332917/a.patch.txt) which fixes this particular issue.

**Comment by wwwlicious** [comment]
@Vertigo093i Thanks for this, will get this updated tonight.

**Comment by Vertigo093i** [comment]
Thank you very much!

P.S. Do not abandon this great plugin. Transforming to NUnit using XSLT is almost a pain.

**Comment by wwwlicious** [comment]
@Vertigo093i You are welcome and pleased someone else finds it useful. Thank you for the patch.

I use/need this plugin every day so no plans to abandon it, quite the opposite in fact. have a few ideas on how it can be extended/improved.
