### ISSUE TITLE
How do I register xUnit.Net Parser “xunit-1.0.4.jar” with Bamboo?

### ISSUE THREAD

**Issue by normanlmfung** [wwwlicious/wwwlicious.bamboo.xunit#5]
How do I register xUnit.Net Parser “xunit-1.0.4.jar” with Bamboo? I tried put it here: Then put it under here: C:\Program Files\Bamboo\atlassian-bamboo\WEB-INF\lib

Think it crashes Bamboo on startup. Not sure how to make "xUnit.Net Parser" available from Bamboo Task

https://marketplace.atlassian.com/apps/1216522/xunit-net-parser?hosting=server&tab=overview https://github.com/wwwlicious/wwwlicious.bamboo.xunit

**Comment by wwwlicious** [comment]
You can either install it from the marketplace or upload the jar file, both via the admin interface within Bamboo

https://marketplace.atlassian.com/apps/1216522/xunit-net-parser?hosting=server&tab=installation

**Comment by normanlmfung** [comment]
Thanks wwwlicious - It's under **"Manage Apps"** the Bamboo version I am working with.
I click "Find new apps", but then Bamboo crashed. It's a separate issue, and I need do a little digging ...

The version I am using is: Continuous integration powered by Atlassian Bamboo version 6.8.0 build 60803 - 30 Jan 19

**Comment by wwwlicious** [comment]
Closing this as resolved. Feel free to reopen if there is still an issue
