### ISSUE TITLE
Starting task 'Xunit' of type 'com.wwwlicious.xunit.xunit:xunitParser' Failing task since test cases were expected but none were found.

### ISSUE THREAD

**Issue by normanlmfung** [wwwlicious/wwwlicious.bamboo.xunit#6]
I configured xunit parser task under my project's Bamboo plan, I ran my plan:
Starting task 'Xunit' of type 'com.wwwlicious.xunit.xunit:xunitParser' Failing task since test cases were expected but none were found.

It dawns on my _xunit **parser**_ only parses test result produced somehow from prev steps?

I tried to add a script task to run xunit tests manually: https://xunit.github.io/docs/getting-started/netcore/cmdline
```

C:\SomeApplication>dotnet test
Build completed.
Test run for C:\SomeApplication\bin\Debug\netcoreapp2.0\YI.LS.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Total tests: 20. Passed: 20. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 4.3114 Seconds
```
So, okay - I can configure a Bamboo Script task to run "**dotnet test**". Now the challenge is: How "dotnet test" to produce an xml result file? And how to feed it to **xunit parser**?

Thanks

Xunit parser: https://marketplace.atlassian.com/apps/1216522/xunit-net-parser?hosting=server&tab=support

**Comment by Vertigo093i** [comment]
> How "dotnet test" to produce an xml result file?

See https://stackoverflow.com/questions/49917144/how-to-publish-results-using-dotnet-test-command

**Comment by normanlmfung** [comment]
Thanks Vertigo.

I tried:
    dotnet test -l:trx;LogFileName=LSTest.xml

Test ran successfully. I have my XML under "TestResults" folder - now how can I feed it to xunit-parser?

**Comment by wwwlicious** [comment]
@devvvy the xunit parser only parses xunit test result formats, not trx test results.
For .net core, you would need to use the [xunit logger](https://github.com/spekt/xunit.testlogger)

The parser expects an ant style path (wildcards allowed) to the xunit xml output files

Not sure if bamboo can parse trx format results anyway (i.e. without requiring the xunit parser task)

**Comment by Vertigo093i** [comment]
> Not sure if bamboo can parse trx format results anyway

Bamboo has the **MSTest Parser** task which is probably able to consume `.trx` results.

**Comment by normanlmfung** [comment]
Thanks gents, I got it working. You need install in test project "XunitXmlTestLogger" (https://github.com/spekt/xunit.testlogger)
Then configure a Script task:
    dotnet test -l:"xunit;LogFileName=Test.xml"
You need set Working Directory to point at your test project, for example: MySoln\MyTestProj

Then configure your xUnit.net Parser task in Bamboo, with xUnit Test Results File/Directory to point at: MySoln\MyTestProj*.xml (Default is: artifacts/**/*.xml)

Thanks for helping!!!

**Comment by wwwlicious** [comment]
Closing this as resolved. Feel free to reopen if there is still an issue
